/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { providers, Signer, ethers } from "ethers";
import React, { useEffect, useState } from "react";
import Web3Modal, { IProviderOptions } from "web3modal";
import GangstaEggs_ImplementationDeployment from "./deployments/hardhat/GangstaEggs_Implementation.json";
import GangstaEggs_ProxyDeployment from "./deployments/hardhat/GangstaEggs_Proxy.json";
import SharedWallet_ImplementationDeployment from "./deployments/hardhat/SharedWallet_Implementation.json";
import SharedWallet_ProxyDeployment from "./deployments/hardhat/SharedWallet_Proxy.json";
import { GangstaChicks } from "./typechain/GangstaChicks";
import { GangstaChicks__factory } from "./typechain/factories/GangstaChicks__factory";
import SharedWalletDeployment from "./deployments/hardhat/SharedWallet.json";
import { SharedWallet } from "./typechain/SharedWallet";
import { SharedWallet__factory } from "./typechain/factories/SharedWallet__factory";
import { RoleBasedAccess } from "./typechain/RoleBasedAccess";
import { RoleBasedAccess__factory } from "./typechain/factories/RoleBasedAccess__factory";
import GangstaEggsDeployment from "./deployments/hardhat/GangstaEggs.json";
import { GangstaEggs } from "./typechain/GangstaEggs";
import { GangstaEggs__factory } from "./typechain/factories/GangstaEggs__factory";
import { PriceReference } from "./typechain/PriceReference";
import { PriceReference__factory } from "./typechain/factories/PriceReference__factory";
import { PaymentSplitter } from "./typechain/PaymentSplitter";
import { PaymentSplitter__factory } from "./typechain/factories/PaymentSplitter__factory";
import { ERC721 } from "./typechain/ERC721";
import { ERC721__factory } from "./typechain/factories/ERC721__factory";

const emptyContract = {
    instance: undefined,
    factory: undefined
};
const defaultProvider: providers.Provider | undefined = undefined;
export const ProviderContext = React.createContext<[providers.Provider | undefined, React.Dispatch<React.SetStateAction<providers.Provider | undefined>>]>([defaultProvider, () => { }]);
const defaultCurrentAddress: string = "";
export const CurrentAddressContext = React.createContext<[string, React.Dispatch<React.SetStateAction<string>>]>([defaultCurrentAddress, () => { }]);
const defaultSigner: Signer | undefined = undefined;
export const SignerContext = React.createContext<[Signer | undefined, React.Dispatch<React.SetStateAction<Signer | undefined>>]>([defaultSigner, () => { }]);
const defaultSymfoniContext: SymfoniContextInterface = {
    currentHardhatProvider: "",
    init: () => { throw Error("Symfoni context not initialized") },
    loading: false,
    messages: [],
    providers: []
};
export const SymfoniContext = React.createContext<SymfoniContextInterface>(defaultSymfoniContext);
export const GangstaEggs_ImplementationContext = React.createContext<SymfoniGangstaEggs>(emptyContract);
export const GangstaEggs_ProxyContext = React.createContext<SymfoniGangstaEggs>(emptyContract);
export const SharedWallet_ImplementationContext = React.createContext<SymfoniSharedWallet>(emptyContract);
export const SharedWallet_ProxyContext = React.createContext<SymfoniSharedWallet>(emptyContract);
export const GangstaChicksContext = React.createContext<SymfoniGangstaChicks>(emptyContract);
export const SharedWalletContext = React.createContext<SymfoniSharedWallet>(emptyContract);
export const RoleBasedAccessContext = React.createContext<SymfoniRoleBasedAccess>(emptyContract);
export const GangstaEggsContext = React.createContext<SymfoniGangstaEggs>(emptyContract);
export const PriceReferenceContext = React.createContext<SymfoniPriceReference>(emptyContract);
export const PaymentSplitterContext = React.createContext<SymfoniPaymentSplitter>(emptyContract);
export const ERC721Context = React.createContext<SymfoniERC721>(emptyContract);

export interface SymfoniContextInterface {
    init: (provider?: string) => void;
    loading: boolean;
    messages: string[];
    currentHardhatProvider: string;
    providers: string[];
}

export interface SymfoniProps {
    autoInit?: boolean;
    showLoading?: boolean;
    loadingComponent?: React.ReactNode;
}

export interface SymfoniGangstaEggs {
    instance?: GangstaEggs;
    factory?: GangstaEggs__factory;
}

export interface SymfoniGangstaEggs {
    instance?: GangstaEggs;
    factory?: GangstaEggs__factory;
}

export interface SymfoniSharedWallet {
    instance?: SharedWallet;
    factory?: SharedWallet__factory;
}

export interface SymfoniSharedWallet {
    instance?: SharedWallet;
    factory?: SharedWallet__factory;
}

export interface SymfoniGangstaChicks {
    instance?: GangstaChicks;
    factory?: GangstaChicks__factory;
}

export interface SymfoniSharedWallet {
    instance?: SharedWallet;
    factory?: SharedWallet__factory;
}

export interface SymfoniRoleBasedAccess {
    instance?: RoleBasedAccess;
    factory?: RoleBasedAccess__factory;
}

export interface SymfoniGangstaEggs {
    instance?: GangstaEggs;
    factory?: GangstaEggs__factory;
}

export interface SymfoniPriceReference {
    instance?: PriceReference;
    factory?: PriceReference__factory;
}

export interface SymfoniPaymentSplitter {
    instance?: PaymentSplitter;
    factory?: PaymentSplitter__factory;
}

export interface SymfoniERC721 {
    instance?: ERC721;
    factory?: ERC721__factory;
}

export const Symfoni: React.FC<SymfoniProps> = ({
    showLoading = true,
    autoInit = true,
    ...props
}) => {
    const [initializeCounter, setInitializeCounter] = useState(0);
    const [currentHardhatProvider, setCurrentHardhatProvider] = useState("");
    const [loading, setLoading] = useState(false);
    const [messages, setMessages] = useState<string[]>([]);
    const [signer, setSigner] = useState<Signer | undefined>(defaultSigner);
    const [provider, setProvider] = useState<providers.Provider | undefined>(defaultProvider);
    const [currentAddress, setCurrentAddress] = useState<string>(defaultCurrentAddress);
    const [fallbackProvider] = useState<string | undefined>(undefined);
    const [providerPriority, setProviderPriority] = useState<string[]>(["web3modal", "hardhat"]);
    const [GangstaEggs_Implementation, setGangstaEggs_Implementation] = useState<SymfoniGangstaEggs>(emptyContract);
    const [GangstaEggs_Proxy, setGangstaEggs_Proxy] = useState<SymfoniGangstaEggs>(emptyContract);
    const [SharedWallet_Implementation, setSharedWallet_Implementation] = useState<SymfoniSharedWallet>(emptyContract);
    const [SharedWallet_Proxy, setSharedWallet_Proxy] = useState<SymfoniSharedWallet>(emptyContract);
    const [GangstaChicks, setGangstaChicks] = useState<SymfoniGangstaChicks>(emptyContract);
    const [SharedWallet, setSharedWallet] = useState<SymfoniSharedWallet>(emptyContract);
    const [RoleBasedAccess, setRoleBasedAccess] = useState<SymfoniRoleBasedAccess>(emptyContract);
    const [GangstaEggs, setGangstaEggs] = useState<SymfoniGangstaEggs>(emptyContract);
    const [PriceReference, setPriceReference] = useState<SymfoniPriceReference>(emptyContract);
    const [PaymentSplitter, setPaymentSplitter] = useState<SymfoniPaymentSplitter>(emptyContract);
    const [ERC721, setERC721] = useState<SymfoniERC721>(emptyContract);
    useEffect(() => {
        if (messages.length > 0)
            console.debug(messages.pop())
    }, [messages])

    const getProvider = async (): Promise<{ provider: providers.Provider, hardhatProviderName: string } | undefined> => {
        let hardhatProviderName = "Not set";
        let _providerPriority = [...providerPriority];
        // Fallback provider
        if (fallbackProvider && autoInit && initializeCounter === 0) {
            if (localStorage.getItem("WEB3_CONNECT_CACHED_PROVIDER") === null) {
                _providerPriority = _providerPriority.sort((a, b) => {
                    return a === fallbackProvider ? -1 : b === fallbackProvider ? 1 : 0;
                })
            }
        }
        const provider = await _providerPriority.reduce(async (maybeProvider: Promise<providers.Provider | undefined>, providerIdentification) => {
            let foundProvider = await maybeProvider
            if (foundProvider) {
                return Promise.resolve(foundProvider)
            }
            else {
                switch (providerIdentification.toLowerCase()) {
                    case "web3modal":
                        try {
                            const provider = await getWeb3ModalProvider()
                            const web3provider = new ethers.providers.Web3Provider(provider);
                            hardhatProviderName = "web3modal";
                            return Promise.resolve(web3provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        }
                    case "hardhat":
                        try {
                            const provider = new ethers.providers.JsonRpcProvider({
                                url: "http://127.0.0.1:8545",
                            });
                            hardhatProviderName = "hardhat";
                            return Promise.resolve(provider)
                        } catch (error) {
                            return Promise.resolve(undefined)
                        } default:
                        return Promise.resolve(undefined)
                }
            }
        }, Promise.resolve(undefined)) // end reduce
        return provider ? { provider, hardhatProviderName } : undefined
    };
    const getSigner = async (_provider: providers.Provider, hardhatProviderName: string): Promise<Signer | undefined> => {
        switch (hardhatProviderName) {
            case "web3modal":
                const web3provider = _provider as ethers.providers.Web3Provider
                return await web3provider.getSigner()
            case "hardhat":
                return ethers.Wallet.fromMnemonic("test test test test test test test test test test test junk").connect(_provider)
            default:
                return undefined
        }
    };
    const getWeb3ModalProvider = async (): Promise<any> => {
        const providerOptions: IProviderOptions = {

        };
        const web3Modal = new Web3Modal({
            // network: "mainnet",
            cacheProvider: false,
            providerOptions, // required
        });
        return await web3Modal.connect();
    };

    useEffect(() => {
        let subscribed = true
        const doAsync = async () => {
            const finish = (text: string) => {
                setLoading(false)
                setMessages(old => [...old, text])
            }
            const finishWithContracts = (text: string) => {
                setGangstaEggs_Implementation(getGangstaEggs_Implementation(_provider, _signer))
                setGangstaEggs_Proxy(getGangstaEggs_Proxy(_provider, _signer))
                setSharedWallet_Implementation(getSharedWallet_Implementation(_provider, _signer))
                setSharedWallet_Proxy(getSharedWallet_Proxy(_provider, _signer))
                setGangstaChicks(getGangstaChicks(_provider, _signer))
                setSharedWallet(getSharedWallet(_provider, _signer))
                setRoleBasedAccess(getRoleBasedAccess(_provider, _signer))
                setGangstaEggs(getGangstaEggs(_provider, _signer))
                setPriceReference(getPriceReference(_provider, _signer))
                setPaymentSplitter(getPaymentSplitter(_provider, _signer))
                setERC721(getERC721(_provider, _signer))
                finish(text)
            }
            if (!autoInit && initializeCounter === 0) return finish("Auto init turned off.")
            setLoading(true)
            setMessages(old => [...old, "Initiating Symfoni React"])
            const providerObject = await getProvider() // getProvider can actually return undefined, see issue https://github.com/microsoft/TypeScript/issues/11094

            if (!subscribed || !providerObject) return finish("No provider or signer.")
            const _provider = providerObject.provider
            setProvider(_provider)
            setMessages(old => [...old, "Useing " + providerObject.hardhatProviderName])
            setCurrentHardhatProvider(providerObject.hardhatProviderName)
            const _signer = await getSigner(_provider, providerObject.hardhatProviderName);

            if (!subscribed || !_signer) return finishWithContracts("Provider, without signer.")
            setSigner(_signer)
            setMessages(old => [...old, "Useing signer"])
            const address = await _signer.getAddress()

            if (!subscribed || !address) return finishWithContracts("Provider and signer, without address.")
            setCurrentAddress(address)

            return finishWithContracts("Completed Symfoni context initialization.")
        };
        doAsync();
        return () => { subscribed = false }
    }, [initializeCounter])

    const getGangstaEggs_Implementation = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = GangstaEggs_ImplementationDeployment.receipt.contractAddress
        const instance = _signer ? GangstaEggs__factory.connect(contractAddress, _signer) : GangstaEggs__factory.connect(contractAddress, _provider)
        const contract: SymfoniGangstaEggs = {
            instance: instance,
            factory: _signer ? new GangstaEggs__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getGangstaEggs_Proxy = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = GangstaEggs_ProxyDeployment.receipt.contractAddress
        const instance = _signer ? GangstaEggs__factory.connect(contractAddress, _signer) : GangstaEggs__factory.connect(contractAddress, _provider)
        const contract: SymfoniGangstaEggs = {
            instance: instance,
            factory: _signer ? new GangstaEggs__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getSharedWallet_Implementation = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = SharedWallet_ImplementationDeployment.receipt.contractAddress
        const instance = _signer ? SharedWallet__factory.connect(contractAddress, _signer) : SharedWallet__factory.connect(contractAddress, _provider)
        const contract: SymfoniSharedWallet = {
            instance: instance,
            factory: _signer ? new SharedWallet__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getSharedWallet_Proxy = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = SharedWallet_ProxyDeployment.receipt.contractAddress
        const instance = _signer ? SharedWallet__factory.connect(contractAddress, _signer) : SharedWallet__factory.connect(contractAddress, _provider)
        const contract: SymfoniSharedWallet = {
            instance: instance,
            factory: _signer ? new SharedWallet__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getGangstaChicks = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? GangstaChicks__factory.connect(ethers.constants.AddressZero, _signer) : GangstaChicks__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniGangstaChicks = {
            instance: instance,
            factory: _signer ? new GangstaChicks__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getSharedWallet = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = SharedWalletDeployment.receipt.contractAddress
        const instance = _signer ? SharedWallet__factory.connect(contractAddress, _signer) : SharedWallet__factory.connect(contractAddress, _provider)
        const contract: SymfoniSharedWallet = {
            instance: instance,
            factory: _signer ? new SharedWallet__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getRoleBasedAccess = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? RoleBasedAccess__factory.connect(ethers.constants.AddressZero, _signer) : RoleBasedAccess__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniRoleBasedAccess = {
            instance: instance,
            factory: _signer ? new RoleBasedAccess__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getGangstaEggs = (_provider: providers.Provider, _signer?: Signer) => {

        const contractAddress = GangstaEggsDeployment.receipt.contractAddress
        const instance = _signer ? GangstaEggs__factory.connect(contractAddress, _signer) : GangstaEggs__factory.connect(contractAddress, _provider)
        const contract: SymfoniGangstaEggs = {
            instance: instance,
            factory: _signer ? new GangstaEggs__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getPriceReference = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? PriceReference__factory.connect(ethers.constants.AddressZero, _signer) : PriceReference__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniPriceReference = {
            instance: instance,
            factory: _signer ? new PriceReference__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getPaymentSplitter = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? PaymentSplitter__factory.connect(ethers.constants.AddressZero, _signer) : PaymentSplitter__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniPaymentSplitter = {
            instance: instance,
            factory: _signer ? new PaymentSplitter__factory(_signer) : undefined,
        }
        return contract
    }
        ;
    const getERC721 = (_provider: providers.Provider, _signer?: Signer) => {
        let instance = _signer ? ERC721__factory.connect(ethers.constants.AddressZero, _signer) : ERC721__factory.connect(ethers.constants.AddressZero, _provider)
        const contract: SymfoniERC721 = {
            instance: instance,
            factory: _signer ? new ERC721__factory(_signer) : undefined,
        }
        return contract
    }
        ;

    const handleInitProvider = (provider?: string) => {
        if (provider) {
            setProviderPriority(old => old.sort((a, b) => {
                return a === provider ? -1 : b === provider ? 1 : 0;
            }))
        }
        setInitializeCounter(initializeCounter + 1)
    }
    return (
        <SymfoniContext.Provider value={{ init: (provider) => handleInitProvider(provider), providers: providerPriority, currentHardhatProvider, loading, messages }}>
            <ProviderContext.Provider value={[provider, setProvider]}>
                <SignerContext.Provider value={[signer, setSigner]}>
                    <CurrentAddressContext.Provider value={[currentAddress, setCurrentAddress]}>
                        <GangstaEggs_ImplementationContext.Provider value={GangstaEggs_Implementation}>
                            <GangstaEggs_ProxyContext.Provider value={GangstaEggs_Proxy}>
                                <SharedWallet_ImplementationContext.Provider value={SharedWallet_Implementation}>
                                    <SharedWallet_ProxyContext.Provider value={SharedWallet_Proxy}>
                                        <GangstaChicksContext.Provider value={GangstaChicks}>
                                            <SharedWalletContext.Provider value={SharedWallet}>
                                                <RoleBasedAccessContext.Provider value={RoleBasedAccess}>
                                                    <GangstaEggsContext.Provider value={GangstaEggs}>
                                                        <PriceReferenceContext.Provider value={PriceReference}>
                                                            <PaymentSplitterContext.Provider value={PaymentSplitter}>
                                                                <ERC721Context.Provider value={ERC721}>
                                                                    {showLoading && loading ?
                                                                        props.loadingComponent
                                                                            ? props.loadingComponent
                                                                            : <div>
                                                                                {messages.map((msg, i) => (
                                                                                    <p key={i}>{msg}</p>
                                                                                ))}
                                                                            </div>
                                                                        : props.children
                                                                    }
                                                                </ERC721Context.Provider >
                                                            </PaymentSplitterContext.Provider >
                                                        </PriceReferenceContext.Provider >
                                                    </GangstaEggsContext.Provider >
                                                </RoleBasedAccessContext.Provider >
                                            </SharedWalletContext.Provider >
                                        </GangstaChicksContext.Provider >
                                    </SharedWallet_ProxyContext.Provider >
                                </SharedWallet_ImplementationContext.Provider >
                            </GangstaEggs_ProxyContext.Provider >
                        </GangstaEggs_ImplementationContext.Provider >
                    </CurrentAddressContext.Provider>
                </SignerContext.Provider>
            </ProviderContext.Provider>
        </SymfoniContext.Provider>
    )

};
